# Generated by Django 3.0.3 on 2020-02-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
    ]
